import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import hpp from 'hpp';
import mongoSanitize from 'express-mongo-sanitize';
import morgan from 'morgan';
import cookieParser from 'cookie-parser';
import 'express-async-errors';

import authRoutes from './routes/authRoutes.js';
import userRoutes from './routes/userRoutes.js';
import bookRoutes from './routes/bookRoutes.js';
import adminRoutes from './routes/adminRoutes.js';
import verificationRoutes from './routes/verificationRoutes.js';
import notificationRoutes from './routes/notificationRoutes.js';
import earningsRoutes from './routes/earningsRoutes.js';
import creativeRoutes from './routes/creativeRoutes.js';
import proRoutes from './routes/proRoutes.js';
import creditRoutes from './routes/creditRoutes.js';
import withdrawalRoutes from './routes/withdrawalRoutes.js';
import contactRoutes from './routes/contactRoutes.js';
import { errorHandler, notFound } from './middleware/errorMiddleware.js';

const app = express();
app.use(cors({ origin: [process.env.FRONTEND_URL, 'http://127.0.0.1:5173', 'http://localhost:5173'], credentials: true }));
app.use(helmet({ crossOriginResourcePolicy: false }));
app.use(express.json({ limit: '10mb' }));
app.use(express.urlencoded({ extended: true }));
app.use(cookieParser());
app.use(mongoSanitize());
app.use(hpp());
app.use(rateLimit({ windowMs: 15 * 60 * 1000, max: 5000 }));
if (process.env.NODE_ENV !== 'production') app.use(morgan('dev'));
app.use('/uploads', express.static('uploads'));

app.get('/api/health', (req, res) => res.json({ ok: true, app: 'LIYAMU API' }));
app.use('/api/auth', authRoutes);
app.use('/api/users', userRoutes);
app.use('/api/books', bookRoutes);
app.use('/api/admin', adminRoutes);
app.use('/api/verifications', verificationRoutes);
app.use('/api/notifications', notificationRoutes);
app.use('/api/earnings', earningsRoutes);
app.use('/api/creative', creativeRoutes);
app.use('/api/pro', proRoutes);
app.use('/api/credits', creditRoutes);
app.use('/api/withdrawals', withdrawalRoutes);
app.use('/api/contacts', contactRoutes);
app.use(notFound);
app.use(errorHandler);

export default app;
